#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandrakelinux
# Module          : netprofile
# File            : clone-netprofile
# Version         : $Id: clone-netprofile,v 1.3 2004/06/23 23:33:32 flepied Exp $
# Author          : Frederic Lepied
# Created On      : Fri Mar 21 23:23:34 2003
# Purpose         : clone a profile
#---------------------------------------------------------------

if [[ $# != 2 ]]; then
    echo "usage: `basename $0` <source profile> <dest profile>" 1>&2
    exit 1
fi

TOP=${TOP=/etc/netprofile}

rm -rf $TOP/profiles/"$2"

mkdir -p $TOP/profiles/"$2"/files

PROFILE=default

if [[ -r $TOP/current ]]; then
    . $TOP/current
fi

if [[ "$1" = "$PROFILE" ]]; then
    save-netprofile "$2"
else
    tar c -C $TOP/profiles/"$1" . | tar x -C $TOP/profiles/"$2"
fi

# clone-netprofile ends here
