#############################################################################
# File		: Makefile
# Package	: netprofile
# Author	: Frederic Lepied
# Created on	: Mon Sep 30 13:20:18 1999
# Version	: $Id: Makefile,v 1.7 2005/12/06 21:58:49 flepied Exp $
# Purpose	: rules to manage the files.
#############################################################################

BINDIR=/sbin
ETCDIR=/etc/netprofile
BASHDIR=/etc/bash_completion.d
IFUPDIR=/etc/sysconfig/network-scripts/ifup.d

BINFILES=netprofile set-netprofile clone-netprofile save-netprofile \
 add-to-netprofile remove-from-netprofile
FILES= $(BINFILES) \
 netprofile.spec Makefile ChangeLog list bash.completion netprofile.ifup

PACKAGE=netprofile
VERSION:=$(shell rpm -q --qf %{VERSION} --specfile $(PACKAGE).spec)
RELEASE:=$(shell rpm -q --qf %{RELEASE} --specfile $(PACKAGE).spec)
TAG := $(shell echo "V$(VERSION)_$(RELEASE)" | tr -- '-.' '__')

RPMOPT = --clean --rmspec

all:

clean:
	rm -f *~

install:
	-mkdir -p $(DESTDIR)$(BINDIR) $(DESTDIR)$(ETCDIR)/profiles $(DESTDIR)/$(BASHDIR) $(DESTDIR)$(IFUPDIR)
	for f in $(BINFILES); do install $$f $(DESTDIR)$(BINDIR); done
	install -m 644 list  $(DESTDIR)$(ETCDIR)/
	install -m 644 bash.completion $(DESTDIR)/$(BASHDIR)/$(PACKAGE)
	install -m 755 netprofile.ifup $(DESTDIR)$(IFUPDIR)/netprofile

version:
	@echo "$(VERSION)-$(RELEASE)"

# rules to build a test rpm

localrpm: localdist buildrpm

localdist: cleandist dir localcopy tar

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

dir:
	mkdir $(PACKAGE)-$(VERSION)

localcopy:
	tar c $(FILES) | tar x -C $(PACKAGE)-$(VERSION)

tar:
	tar cvf $(PACKAGE)-$(VERSION).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).tar
	rm -rf $(PACKAGE)-$(VERSION)

buildrpm:
	rpm -ta $(RPMOPT) $(PACKAGE)-$(VERSION).tar.bz2

# rules to build a distributable rpm

rpm: changelog cvstag dist buildrpm

dist: cleandist dir export tar

export:
	cvs export -d $(PACKAGE)-$(VERSION) -r $(TAG) $(PACKAGE)

cvstag:
	cvs tag $(CVSTAGOPT) $(TAG)

changelog: ../common/username
	cvs2cl -U ../common/username -I ChangeLog 
	rm -f ChangeLog.bak
	cvs commit -m "Generated by cvs2cl the `date '+%d_%b'`" ChangeLog

# Makefile ends here
