#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandrakelinux
# Module          : netprofile
# File            : remove-from-netprofile
# Version         : $Id: remove-from-netprofile,v 1.2 2005/03/03 20:19:20 flepied Exp $
# Author          : Frederic Lepied
# Created On      : Thu Jun 24 07:35:55 2004
# Purpose         : remove a file from the control of netprofile
#---------------------------------------------------------------

TOP=${TOP=/etc/netprofile}

if [ $# = 0 ]; then
    echo "usage: `basename $0` <file> [<file>...]" 1>&2
    exit 1
fi

for f in "$@"; do
    if grep -q "^$f$" "$TOP/list"; then
	for d in "$TOP"/profiles/*/files; do
	    rm "$d/$f"
	done
	grep -v "^$f$" "$TOP/list" > "$TOP/list.tmp"
	mv "$TOP/list.tmp" "$TOP/list"
    else
	echo "$f isn't under netprofile management" 1>&2
    fi
done

# remove-from-netprofile ends here
