#!/bin/bash
#---------------------------------------------------------------
# Project         : Mandriva Linux
# Module          : netprofile
# File            : set-netprofile
# Version         : $Id: set-netprofile,v 1.20 2005/12/06 22:02:14 flepied Exp $
# Author          : Frederic Lepied
# Created On      : Fri Mar 21 21:33:06 2003
#---------------------------------------------------------------

NETPROFILE=/etc/netprofile
PROFILES=$NETPROFILE/profiles
MODULES=$NETPROFILE/modules
CURRENT=$NETPROFILE/current
VERBOSE=1

function restore_files {
        PROFILE=$1
        MODULE=$2
        FILES=$3
        # restoring old files
        SAVED_FILES="$PROFILES/$PROFILE/$MODULE.tar.gz"
        echo "(cd / && test -e $SAVED_FILES && tar xpzf $SAVED_FILES)"
}

function save_files {
        PROFILE=$1
        MODULE=$2
        FILES=$3
        # saving files
        #SAVED_FILES="$PROFILES/$PROFILE/$MODULE.tar.gz"
        SAVED_FILES="$PROFILE/$MODULE.tar.gz"
        mkdir -p $PROFILE
        #echo "(cd / && tar cpzf $SAVED_FILES \"$FILES\")"
        tar cpzf $SAVED_FILES $(echo $FILES)
}

function restart_services {
        SERVICES=$1
        for service in $SERVICES; do
                test -e /etc/init.d/$service && echo service $service restart
        done
}

function print_debug {
        if [ "a$VERBOSE" = "a1" ]; then
                echo "$*"
        fi
}

function restore_profile {
        # sets a network profile
        PROFILE=$1
        CURPROFILE=$(cat $CURRENT)
        if [ "a$PROFILE" = "a$CURPROFILE" ]; then
                echo "The profile $PROFILE profile is already active."
                return 1
        fi
        for module in $MODULES/*; do
                # if module is not executable, disable it
                test -x $module || continue
                . $module
                print_debug "Restoring files for $NAME"
                restore_files "$PROFILE" "$NAME" "$FILES"
                print_debug "Restarting services for $NAME"
                restart_services "$SERVICES"
                restore $PROFILE
        done
        # mark current profile as restored
        echo $PROFILE > $CURRENT
}

function save_profile {
        # saves current system settings into a profile
        PROFILE=$1
        for module in $MODULES/*; do
                # if module is not executable, disable it
                test -x $module || continue
                . $module
                print_debug "Saving files for $NAME"
                save_files "$PROFILE" "$NAME" "$FILES"
                save $PROFILE
        done
}

NO_RESTART_NETWORK=

# {{{ boot selection
if [[ -z "$NEWPROFILE" ]]; then
    # Check the kernel command line, profile are selectable
    # right from the boot manager
    eval `cat /proc/cmdline | tr ' ' '\n' | grep PROFILE`
    NEWPROFILE="$PROFILE"
    if [[ -z "$NEWPROFILE" && -x /usr/bin/fbmenu && -d /etc/netprofile/profiles/ ]]; then
        nb_profiles=`ls /etc/netprofile/profiles | wc -l`;
        if [[ "$nb_profiles" == "1" ]]; then
            NEWPROFILE=`basename /etc/netprofile/profiles/*`
        else 
            _procsplash="`cat /proc/splash 2>/dev/null`"
            grep -q silent /proc/cmdline && grep -q silent /proc/splash && _silent="yes"
            if [ -z "$_silent" -o ! -r /proc/splash -o -z "`echo $_procsplash|grep on`" ]; then
                if [[ -x /usr/bin/fbgrab ]]; then
                    rm -f /tmp/bootsplash.png
                    /usr/bin/fbgrab /tmp/bootsplash.png
                fi
            else
                if [[ -z $res ]]; then 
                    res=`fbresolution`
                fi
                if [[ -f /etc/sysconfig/bootsplash ]]; then
                    . /etc/sysconfig/bootsplash
                    theme=$THEME
                    if [[ -f /etc/bootsplash/themes/$theme/config/bootsplash-$res.cfg ]]; then
                        function box() { true; }
                        . /etc/bootsplash/themes/$theme/config/bootsplash-$res.cfg
                    fi
                fi
                if [[ -f $silentjpeg ]]; then
                    rm -f /tmp/bootsplash.png
                    cp -f $silentjpeg /tmp/bootsplash.png
                fi
            fi

            if [[ -r $TOP/current ]]; then
                eval `cat $TOP/current`
            fi
            pushd  /etc/netprofile/profiles/
            if [[ -n "$PROFILE" ]]; then 
                eval `GTK2_RC_FILES=/etc/bootsplash/themes/current/config/gtkrc /usr/bin/fbmenu 10 "Choose a profile" "$PROFILE" * | grep RESULT`
            else 
                eval `GTK2_RC_FILES=/etc/bootsplash/themes/current/config/gtkrc /usr/bin/fbmenu 10 "Choose a profile" * | grep RESULT`
            fi
            if [[ "$_silent" == "yes" ]]; then
                if [[ -f /etc/bootsplash/themes/$theme/config/bootsplash-$res.cfg ]]; then
                    /sbin/splash -s -u 0 /etc/bootsplash/themes/$theme/config/bootsplash-$res.cfg
                fi
            fi
            NEWPROFILE="$RESULT"
            popd
        fi
    fi
fi
# }}}

restore_profile default
save_profile default

exit 0

# make net_applet reload the configuration
# (needs "current" file to be up to date)
PID=`pidof -x net_applet`
[[ -n "$PID" ]] && kill -HUP $PID

# set-netprofile ends here
